apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apigate
  managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        "f:metadata":
          "f:labels":
            .: {}
            "f:app": {}
        "f:spec":
          "f:progressDeadlineSeconds": {}
          "f:replicas": {}
          "f:revisionHistoryLimit": {}
          "f:selector": {}
          "f:strategy":
            "f:rollingUpdate":
              .: {}
              "f:maxSurge": {}
              "f:maxUnavailable": {}
            "f:type": {}
          "f:template":
            "f:metadata":
              "f:labels":
                .: {}
                "f:app": {}
            "f:spec":
              "f:containers":
                'k:{"name":"softales-backend-1"}':
                  .: {}
                  "f:image": {}
                  "f:imagePullPolicy": {}
                  "f:name": {}
                  "f:resources": {}
                  "f:terminationMessagePath": {}
                  "f:terminationMessagePolicy": {}
              "f:dnsPolicy": {}
              "f:restartPolicy": {}
              "f:schedulerName": {}
              "f:securityContext": {}
              "f:terminationGracePeriodSeconds": {}
      manager: GoogleCloudConsole
      operation: Update
      time: "2022-12-22T16:55:06Z"
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        "f:metadata":
          "f:annotations":
            .: {}
            "f:deployment.kubernetes.io/revision": {}
        "f:status":
          "f:availableReplicas": {}
          "f:conditions":
            .: {}
            'k:{"type":"Available"}':
              .: {}
              "f:lastTransitionTime": {}
              "f:lastUpdateTime": {}
              "f:message": {}
              "f:reason": {}
              "f:status": {}
              "f:type": {}
            'k:{"type":"Progressing"}':
              .: {}
              "f:lastTransitionTime": {}
              "f:lastUpdateTime": {}
              "f:message": {}
              "f:reason": {}
              "f:status": {}
              "f:type": {}
          "f:observedGeneration": {}
          "f:readyReplicas": {}
          "f:replicas": {}
          "f:updatedReplicas": {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: "2022-12-22T16:55:19Z"
  name: apigate
  namespace: default-5
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apigate
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: apigate
    spec:
      containers:
        - image: gcr.io/encoded-aspect-371604/github.com/huamanangel/softales_backend
          imagePullPolicy: IfNotPresent
          name: softales-backend-1
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: apigate
  managedFields:
    - apiVersion: autoscaling/v2
      fieldsType: FieldsV1
      fieldsV1:
        "f:metadata":
          "f:labels":
            .: {}
            "f:app": {}
        "f:spec":
          "f:maxReplicas": {}
          "f:metrics": {}
          "f:minReplicas": {}
          "f:scaleTargetRef":
            "f:apiVersion": {}
            "f:kind": {}
            "f:name": {}
      manager: GoogleCloudConsole
      operation: Update
      time: "2022-12-22T16:55:06Z"
    - apiVersion: autoscaling/v2
      fieldsType: FieldsV1
      fieldsV1:
        "f:status":
          "f:conditions":
            .: {}
            'k:{"type":"AbleToScale"}':
              .: {}
              "f:lastTransitionTime": {}
              "f:message": {}
              "f:reason": {}
              "f:status": {}
              "f:type": {}
            'k:{"type":"ScalingActive"}':
              .: {}
              "f:lastTransitionTime": {}
              "f:message": {}
              "f:reason": {}
              "f:status": {}
              "f:type": {}
            'k:{"type":"ScalingLimited"}':
              .: {}
              "f:lastTransitionTime": {}
              "f:message": {}
              "f:reason": {}
              "f:status": {}
              "f:type": {}
          "f:currentMetrics": {}
          "f:currentReplicas": {}
          "f:desiredReplicas": {}
      manager: vpa-recommender
      operation: Update
      subresource: status
      time: "2022-12-22T16:55:21Z"
  name: apigate-hpa-vctn
  namespace: default-5
spec:
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 80
          type: Utilization
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apigate
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: apigate
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        "f:metadata":
          "f:labels":
            .: {}
            "f:app": {}
        "f:spec":
          "f:allocateLoadBalancerNodePorts": {}
          "f:externalTrafficPolicy": {}
          "f:internalTrafficPolicy": {}
          "f:ports":
            .: {}
            'k:{"port":80,"protocol":"TCP"}':
              .: {}
              "f:port": {}
              "f:protocol": {}
              "f:targetPort": {}
          "f:selector": {}
          "f:sessionAffinity": {}
          "f:type": {}
      manager: GoogleCloudConsole
      operation: Update
      time: "2022-12-22T17:00:36Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        "f:metadata":
          "f:finalizers":
            .: {}
            'v:"service.kubernetes.io/load-balancer-cleanup"': {}
        "f:status":
          "f:loadBalancer":
            "f:ingress": {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: "2022-12-22T17:01:16Z"
  name: apigate-service
  namespace: default-5
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.28.2.147
  clusterIPs:
    - 10.28.2.147
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 30014
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: apigate
  sessionAffinity: None
  type: LoadBalancer
